# Generated by Django 4.0.3 on 2022-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('time', models.IntegerField()),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('sex', models.BooleanField()),
                ('mobile', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('steak', models.IntegerField()),
                ('fish', models.IntegerField()),
                ('chicken', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('sex', models.BooleanField()),
                ('mobile', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=60)),
                ('staff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('time', models.IntegerField()),
                ('vacancy', models.IntegerField()),
            ],
        ),
    ]
